name: Release

on: workflow_dispatch

env:
  PYTHON_VERSION: "3.12"
  POETRY_VERSION: "==1.8.3"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.0
        with:
          python_version: ${{env.PYTHON_VERSION}}
          poetry_version: ${{env.POETRY_VERSION}}
          pypi_token: ${{ secrets.PYPI_TOKEN }}
